### ISSUE TITLE
Нет подключения к http://localhost:9999 

### ISSUE THREAD

**Issue by Denis-Zhigun** [Denis-Zhigun/aga-2-1#1]
Описание проблемы: Нет подключения к http://localhost:9999 

Шаги:
1. При запуске тестов в IDE не происходит подключение к сайту http://localhost:9999 - https://disk.yandex.ru/i/Vcjwt4eGejwEGQ
2. IDE при запуске тестов выдает ошибку - https://disk.yandex.ru/i/jeJvxdzXZCG-Yw

Окружение:
ОС: Windows 8.1
Браузер Chrome Версия 89.0.4389.128 (Официальная сборка), (64 бит)

**Comment by andrew-pahomov** [comment]
Добрый день, необходимо убедиться, что на локальной машине был запущен тестируемый сервис на порту 9999.

**Comment by Denis-Zhigun** [comment]
спасибо
